// Copyright (c) 2026 The Assentian-PQE developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

// SNTI SECURITY FIX (audit 2 Jul 2026): tests for CXMSSSigner's
// wallet-native ownership-stamp protection. Before this fix, only
// mining/imported trees ever got a xmss_tree_ledger.h archive -- wallet
// addresses from getnewxmssaddress had none, so a wallet.dat restored to a
// second device could sign the same one-time address twice with no local
// way to detect it (see job_queue.md, audit 2 Jul 2026, "TEMUAN PALING
// SERIUS"). These tests cover: ledger seeded at generation time, legacy-key
// migration at wallet load, and -- most importantly -- that a native
// address genuinely stays one-time-use once it is ledger-backed (the
// ledger alone allows up to 1024 leaves, which would silently reintroduce
// leaf reuse for wallet keys if not explicitly guarded).

#include <test/util/setup_common.h>
#include <wallet/xmss_signer.h>
#include <xmss_bridge.h>
#include <xmss_miner_state.h>
#include <xmss_tree_ledger.h>
#include <uint256.h>
#include <util/fs.h>

#include <boost/test/unit_test.hpp>

#include <cstring>
#include <vector>

namespace wallet {

BOOST_FIXTURE_TEST_SUITE(xmss_signer_tests, BasicTestingSetup)

static uint256 FakeHash256(uint8_t fill)
{
    return uint256(std::vector<unsigned char>(32, fill));
}

BOOST_AUTO_TEST_CASE(native_key_gets_ledger_at_generation)
{
    CXMSSSigner signer;
    std::vector<uint8_t> pubkey = signer.GenerateKey("gen-test");
    BOOST_REQUIRE_EQUAL(pubkey.size(), 64U);

    uint256 root;
    std::memcpy(root.begin(), pubkey.data(), 32);

    // GenerateKey() must seed the unified ledger immediately -- this is
    // the core of the fix: no window where a native key exists without
    // ownership-stamp protection.
    BOOST_CHECK(PoUWv2::XMSSTreeLedgerExists(gArgs.GetDataDirNet(), root));
}

BOOST_AUTO_TEST_CASE(native_key_second_sign_refused)
{
    CXMSSSigner signer;
    std::vector<uint8_t> pubkey = signer.GenerateKey("onetime");
    BOOST_REQUIRE_EQUAL(pubkey.size(), 64U);

    uint256 hash1 = FakeHash256(0x21);
    std::vector<uint8_t> sig1;
    BOOST_CHECK(signer.SignXMSS(hash1, pubkey, sig1));
    BOOST_CHECK(!sig1.empty());
    BOOST_CHECK(signer.IsXMSSKeyRetired(pubkey));

    // Core regression test requested in the design review: a second sign
    // over a DIFFERENT message with the SAME native key must be refused.
    // Before this fix's retired-check-before-ledger-routing guard, a
    // ledger-backed key would have been allowed to sign again (leaf 1),
    // which leaks the WOTS+ private key.
    uint256 hash2 = FakeHash256(0x22);
    std::vector<uint8_t> sig2;
    BOOST_CHECK(!signer.SignXMSS(hash2, pubkey, sig2));
    BOOST_CHECK(sig2.empty());
}

BOOST_AUTO_TEST_CASE(native_key_legacy_migration_at_loadstate)
{
    fs::path datadir = gArgs.GetDataDirNet();

    std::vector<uint8_t> pubkey;
    std::vector<uint8_t> saved_state;
    {
        CXMSSSigner signer1;
        pubkey = signer1.GenerateKey("legacy-sim");
        BOOST_REQUIRE_EQUAL(pubkey.size(), 64U);
        saved_state = signer1.SaveState();
    }

    uint256 root;
    std::memcpy(root.begin(), pubkey.data(), 32);

    // Sanity: GenerateKey() already created a ledger. Delete it to
    // simulate a key that predates this fix (generated by an older
    // binary, before GenerateKey() started seeding the ledger) -- only
    // the wallet.dat blob (saved_state) survives, exactly like a real
    // upgrade scenario.
    BOOST_REQUIRE(PoUWv2::XMSSTreeLedgerExists(datadir, root));
    fs::path ledgerFile = datadir / "xmss_trees" / fs::PathFromString(root.GetHex() + ".dat");
    fs::remove(ledgerFile);
    BOOST_REQUIRE(!PoUWv2::XMSSTreeLedgerExists(datadir, root));

    // Loading the wallet.dat blob into a fresh signer (simulating a node
    // restart on the upgraded binary) must migrate this still-fresh
    // native key back into the ledger without needing a sign attempt.
    CXMSSSigner signer2;
    BOOST_REQUIRE(signer2.LoadState(saved_state));
    BOOST_CHECK(PoUWv2::XMSSTreeLedgerExists(datadir, root));

    uint256 hash = FakeHash256(0x41);
    std::vector<uint8_t> sig;
    BOOST_CHECK(signer2.SignXMSS(hash, pubkey, sig));
    BOOST_CHECK(!sig.empty());
}

BOOST_AUTO_TEST_CASE(imported_key_multi_use_unaffected)
{
    // Regression guard: this fix must NOT change behavior for
    // imported/mining-style trees, which are legitimately multi-use (up
    // to 1024 leaves) -- only wallet-native keys become one-time-use.
    fs::path datadir = gArgs.GetDataDirNet();

    PoUWv2::XMSSMinerState state;
    BOOST_REQUIRE(PoUWv2::BuildNewTree(state));
    BOOST_REQUIRE(PoUWv2::XMSSTreeLedgerInit(datadir, state));

    XMSS::CXMSSKey key;
    BOOST_REQUIRE(key.Load(state.sk));
    std::vector<uint8_t> pubkey = key.GetPubKey();
    BOOST_REQUIRE_EQUAL(pubkey.size(), 64U);

    CXMSSSigner signer;
    BOOST_REQUIRE(signer.AddXMSSKey(pubkey, state.sk));

    uint256 hash1 = FakeHash256(0x51);
    std::vector<uint8_t> sig1;
    BOOST_CHECK(signer.SignXMSS(hash1, pubkey, sig1));
    BOOST_CHECK(!signer.IsXMSSKeyRetired(pubkey));

    // A second sign over a different message must still succeed for an
    // imported/mining tree -- this is what would break if the one-time-use
    // guard were accidentally applied to imported keys too.
    uint256 hash2 = FakeHash256(0x52);
    std::vector<uint8_t> sig2;
    BOOST_CHECK(signer.SignXMSS(hash2, pubkey, sig2));
    BOOST_CHECK(!sig2.empty());
}

BOOST_AUTO_TEST_SUITE_END()

} // namespace wallet
